### PR TITLE
check $term->term_id before using

### PR DESCRIPTION
**Pull request by pthomson**
was getting "Trying to get property of non-object" error

### CODE REVIEW

**Review by swina — COMMENTED** [review]
I will test on a clean installation. Do you have a live installation working? Thank you

**Comment by pthomson** [comment]
Thanks! No, I do not have a WooCommerce site in production yet.. so don’t have this code in production yet.

**Comment by swina** [comment]
I tested locally (development copy of online installation) and looks there are no problems. I will update on svn next week since I want to make some test with conditions you reported giving problems.
Thank you.

**Comment by pthomson** [comment]
thanks for accepting the pull request!

**Pull request merged**
